-- AgriLoad NoSQL Schema Reference (Firestore)
-- This file documents the data model. Actual storage is Firestore (schemaless).
-- Use this as a reference for collection structures and relationships.

-- ============================================================================
-- COLLECTION: users
-- ============================================================================
-- {
--   id: string (auto),
--   name: string,
--   role: "warehouse" | "logistics",
--   phone: string | null,
--   email: string (unique),
--   password_hash: string,
--   created_at: timestamp
-- }

-- ============================================================================
-- COLLECTION: warehouses
-- ============================================================================
-- {
--   id: string (auto),
--   user_id: string -> users.id,
--   name: string,
--   address: string | null,
--   lat: number | null,
--   lng: number | null
-- }

-- ============================================================================
-- COLLECTION: logistics_companies
-- ============================================================================
-- {
--   id: string (auto),
--   user_id: string -> users.id,
--   name: string
-- }

-- ============================================================================
-- COLLECTION: trucks
-- ============================================================================
-- {
--   id: string (auto),
--   logistics_company_id: string -> logistics_companies.id,
--   vehicle_type: "pickup" | "truck_small" | "truck_medium" | "truck_large",
--   plate_number: string,
--   capacity_weight_kg: number,
--   capacity_volume_m3: number | null,
--   length_cm: number | null,          -- interior cargo dimensions
--   width_cm: number | null,
--   height_cm: number | null,
--   status: "available" | "on_trip" | "maintenance"
-- }

-- ============================================================================
-- COLLECTION: pickup_requests
-- ============================================================================
-- {
--   id: string (auto),
--   warehouse_id: string -> warehouses.id,
--   pickup_date: string (ISO date),
--   required_arrival_date: string (ISO date) | null,  -- must arrive before this
--   destination_name: string,
--   destination_lat: number | null,
--   destination_lng: number | null,
--   notes: string | null,
--   status: "pending" | "assigned" | "optimized" | "in_transit" | "completed" | "cancelled",
--   estimated_arrival: timestamp | null,
--   created_at: timestamp
-- }

-- ============================================================================
-- COLLECTION: request_items
-- ============================================================================
-- {
--   id: string (auto),
--   pickup_request_id: string -> pickup_requests.id,
--   commodity_name: string,
--   unit_type: "kg" | "sack" | "pallet",
--   quantity: number,
--   estimated_weight_kg: number | null,
--   length_cm: number | null,
--   width_cm: number | null,
--   height_cm: number | null,
--   stackable: boolean (default false),
--   fragile: boolean (default false)
-- }

-- ============================================================================
-- COLLECTION: transportation_plans
-- ============================================================================
-- {
--   id: string (auto),
--   logistics_company_id: string -> logistics_companies.id,
--   plan_date: string (ISO date),
--   status: "draft" | "optimized" | "approved" | "in_transit" | "completed",
--   total_requests: number,
--   total_trucks_used: number,
--   total_distance_km: number | null,
--   estimated_fuel_liters: number | null,
--   fuel_savings_percent: number | null,
--   created_at: timestamp,
--   approved_at: timestamp | null
-- }

-- ============================================================================
-- COLLECTION: routes
-- ============================================================================
-- {
--   id: string (auto),
--   transportation_plan_id: string -> transportation_plans.id,
--   truck_id: string -> trucks.id,
--   route_date: string (ISO date),
--   status: "planned" | "in_progress" | "completed",
--   total_distance_km: number | null,
--   space_utilization_percent: number | null,
--   weight_utilization_percent: number | null,
--   generated_at: timestamp
-- }

-- ============================================================================
-- COLLECTION: route_stops
-- ============================================================================
-- {
--   id: string (auto),
--   route_id: string -> routes.id,
--   pickup_request_id: string -> pickup_requests.id,
--   stop_sequence: number,
--   stop_type: "pickup" | "dropoff",
--   lat: number | null,
--   lng: number | null,
--   eta: timestamp | null,
--   allocated_weight_kg: number | null,
--   allocated_volume_m3: number | null,
--   status: "pending" | "in_progress" | "completed"
-- }

-- ============================================================================
-- COLLECTION: space_allocations (loading plan per route)
-- ============================================================================
-- {
--   id: string (auto),
--   route_id: string -> routes.id,
--   pickup_request_id: string -> pickup_requests.id,
--   item_id: string -> request_items.id,
--   loading_sequence: number,           -- order to load (1 = first in, last out)
--   position_notes: string | null,      -- e.g. "bottom layer", "top - fragile"
--   weight_kg: number,
--   volume_m3: number
-- }

-- ============================================================================
-- RELATIONSHIPS
-- ============================================================================
-- users 1--1 warehouses | logistics_companies (by role)
-- logistics_companies 1--N trucks
-- warehouses 1--N pickup_requests
-- pickup_requests 1--N request_items
-- logistics_companies 1--N transportation_plans
-- transportation_plans 1--N routes
-- trucks 1--N routes
-- routes 1--N route_stops
-- routes 1--N space_allocations
-- route_stops N--1 pickup_requests
-- space_allocations N--1 request_items
